### PR TITLE
bumped CRA react-scripts, added PWA

### PR DESCRIPTION
**Pull request by zanettin**
# Goals
- bumped CRA `react-scripts` to `1.0.6` 
- added PWA config (`manifest.json`, `service worker`)
- fixed issue #2 mentioned by @DmitryAuine
- adds `yarn` (optional)
- adds `nvmrc` (optional)

### Lighthouse-Score
bildschirmfoto 2017-05-24 um 22 40 43

### fixed issue
As mentioned in issue #2 `es2015` preset will fix the issue. since babel [recommends](https://babeljs.io/docs/plugins/preset-latest/) to use `env` instead of `es2015` or `es2016` i've added this instead.

### CODE REVIEW

**Comment by fredrik-sogaard** [comment]
I'm pretty new to React SSR, but when I try this fork of the repo, I can't get the SSR part to work. I only see `{{SSR}}` if I disable Javascript and navigate or refresh the page. On the demo site this works fine. I see where the `{{SSR}}` is coming from in the code, but not sure why I see this?

I've deployed it to Now here, if you want to test: https://feed-wed-ssr-ogjcilrbiw.now.sh/

Appreciate all input!

**Comment by agungsb** [comment]
@fredrik-sogaard Do you use `npm start` when it happens? I think, the SSR is not working in development server. If you use `npm run start:server` or `npm run now-start` the SSR should work fine.

**Comment by agungsb** [comment]
Hi, @ayroblu ,

Is there any chance to merge this to master? PWA feature is very cool.

**Comment by fredrik-sogaard** [comment]
Yeah, I'm using start:server and I've deployed to Now with the same results. See the link in my comment. 

If I log out the `markup` and `RenderedApp` variables in `universal.js` I see the markup, but it doesn't replace the {{SSR}} in the HTML I looks like.

**Comment by zanettin** [comment]
Hi @fredrik-sogaard 
As @agungsb mentioned: you have to build the app and serve it then in the prod mode like:
```
yarn run build
yarn run now-start

=> open localhost:3001 in a new tab
```
then everything works as expected (also locally).
here is my example app => https://ssr-create-react-app-v2-givngjeeyx.now.sh

and a demo video
juni-10-2017 19-12-23

happy coding 😄

**Comment by fredrik-sogaard** [comment]
Thanks! I figured it out. I tried disabling Javascript from Chrome settings, but that dosen't seem to be the way to go. Blocking js like in the video works fine!

Any pointers on how to handle async data? Or is that outside the scope of this demo?

**Comment by agungsb** [comment]
Hi, @fredrik-sogaard, glad to hear that.

Do you mean prefetch SSR data as described [here](https://reacttraining.com/react-router/web/guides/server-rendering) ?

If yes, I've just done making a simple example of its implementation, and about to make a pull request.. 😁

**Comment by ayroblu** [comment]
Oh, hey, sorry I haven't looked at this sooner, this looks pretty good, perhaps the only thing is your reasoning of why you removed the noscript tag? As an exemplar, its nice to know when js is off I think?

**Comment by ayroblu** [comment]
^ I added noscript tag, merged

**Comment by zanettin** [comment]
@ayroblu sry didn't see your responses 😄  thanks for the merge and the fix 😄

**Pull request merged**
